### ISSUE TITLE
Debugger.html source map issue

### ISSUE THREAD

**Issue by jasonLaster** [tromey/source-map-examples#2]
I'm noticing a mismatch in original/generated mappings in this case:

The bundle debugger.js line 95313 maps to SearchBar.js line 512, when it should map to 513

![](http://g.recordit.co/yptw5eTwdd.gif) 

Here is a gist with the map file and source file: https://gist.github.com/c23616b0dd7d5030a1550aee3b002b69

you likely can reproduce by going to the project and trying as well

**Comment by tromey** [comment]
For the future, it's probably better to file these somewhere else, maybe devtools-core.

I wrote a program to dump the mappings.  It uses zero-based line numbers, per the spec; in that map, line 95312 says:
```
Line 95312
   column 0
   source #681
   orig line 514
   orig column 4
```

Again, zero-based, so the source-map library should report line 515 here.  I don't know how we end up with 512 instead.

Or maybe the bug is going the other direction?  I'm not sure i understand what's happening in that gif.

**Comment by jasonLaster** [comment]
Oh thanks. I'd forgotten about this issue. I think we *solved* it w/ symmetric bps... but yeah...

**Comment by tromey** [comment]
Going to close it then; re-file elsewhere if you encounter it again.
